NiñasProject/urls.py
from django.contrib import admin
from django.urls import path, include

import usuarios

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("usuarios.urls")),
    path('', include("cursos.urls")),
    path('coordinadora/', include("coordinacion.urls"))
]

coordinacion/urls.py
from django.urls import path, include

from coordinacion import views

app_name = 'coordinadora'
urlpatterns = [
    path('inicio/', views.CoordinadoraInicioView.as_view(), name='inicio_coordinadora'),

]

cursos/urls.py
from django.urls import path, include

from cursos import views

app_name = 'cursos'
urlpatterns = [
    path('<int:curso_id>/curso/', views.CursoView.as_view(), name='curso'),
    path('mis_cursos/', views.MisCursosView.as_view(), name='mis_cursos')
]

usuarios/urls.py
from django.urls import path, include

from usuarios import views

app_name = 'usuarios'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout')
]

coordinacion/models.py
from django.db import models

# Create your models here.

cursos/models.py
from django.db import models

# Create your models here.
from usuarios.models import User


class Tema(models.Model):
    nombre = models.CharField(max_length=50)


class Curso(models.Model):
    nombre = models.CharField(max_length=100)
    profesoras = models.ManyToManyField(User, related_name="profesoras", blank=True)
    voluntarias = models.ManyToManyField(User, related_name="voluntarias", blank=True)
    alumnas = models.ManyToManyField(User, related_name="alumnas", blank=True)
    tema = models.ManyToManyField(Tema, related_name="tags", blank=True)

usuarios/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class User(AbstractUser):
    es_profesora = models.BooleanField('estado de profesora', default=False)
    es_voluntaria = models.BooleanField('estado de voluntaria', default=False)
    es_coordinadora = models.BooleanField('estado de coordinadora', default=False)
    es_alumna = models.BooleanField('estado de alumna', default=False)
    model_pic = models.ImageField(upload_to='media/imagenes/', default='pic_folder/None/no-img.jpg')

    def get_menu_items(self):
        items_dict = {
            'profesora': [('Mis cursos', reverse('usuarios:index'))],
            'voluntaria': [('Mis cursos', reverse('usuarios:index'))],
            'alumna:': [('Ver curso', reverse('usuarios:index'))],
            'coordinadora': [('Mis cursos', reverse('usuarios:index')),
                             ('Modo coordinadora', reverse('coordinadora:inicio_coordinadora'))]
        }
        if self.es_coordinadora:
            return items_dict['coordinadora']
        elif self.es_profesora:
            return items_dict['profesora']
        elif self.es_voluntaria:
            return items_dict['voluntaria']
        elif self.es_alumna:
            return items_dict['alumna:']

coordinacion/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

# Create your views here.
from django.views import View


class CoordinadoraInicioView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'coordinacion/inicio_coordinadora.html')

cursos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views import View

from cursos.models import Curso
from usuarios.models import User


class CursoView(LoginRequiredMixin, View):
    login_url = 'usuarios:login'
    redirect_field_name = ''

    def get(self, request, **kwargs,):
        if request.user.es_profesora or request.user.es_voluntaria:
            # return HttpResponseRedirect(reverse('cursos:mis_cursos'))
            pass
        else:
            return render(request,'cursos/inicio_curso.html')

    '''def get(self):
        #como conseguir los parametros que mando por url.
        self.kwargs['curso_id']'''


class MisCursosView(LoginRequiredMixin, View):
    login_url = 'usuarios:login'
    redirect_field_name = ''

    def get(self, request):
        if request.user.es_alumna:
            return HttpResponseRedirect(reverse('usuarios:index'))

        else:
            cursos = self.get_cursos(request.user.username)
            return render(request, 'cursos/mis_cursos.html', {'cursos': cursos})

    def get_cursos(self, username):
        """
        Método que entrega los cursos en los que username es docente
        :param username: usuario a buscar
        :return: lista de cursos
        """
        usuaria = User.objects.get(username=username)
        if usuaria.es_profesora:
            cursos = Curso.objects.filter(profesoras__in=[usuaria])
        else:
            cursos = Curso.objects.filter(voluntarias__in=[usuaria])
        return list(cursos)

usuarios/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views import View

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.cache import never_cache
from cursos.models import Curso
from usuarios.models import User


class IndexView(LoginRequiredMixin, View):
    login_url = 'usuarios:login'
    redirect_field_name = ''

    def get(self, request):

        if request.user.es_profesora or request.user.es_voluntaria:
            return HttpResponseRedirect(reverse('cursos:mis_cursos'))
        elif request.user.es_alumna:
            curso_id = self.get_curso_estudiante(request.user.username)
            return HttpResponseRedirect(reverse('cursos:curso', args='1'))
        else:
            return render(request, 'cursos/pagina_error.html', {
                'error_message': "El usuario no tiene tipo"
            })

    def get_curso_estudiante(self, username):
        usuaria = User.objects.filter(username=username)
        cursos = Curso.objects.filter(alumnas__in=usuaria)
        return cursos[0].id


class LoginView(View):

    @never_cache
    def get(self, request):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('usuarios:index'))
        return render(request, 'registration/login.html')

    def post(self, request):

        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return HttpResponseRedirect(reverse('usuarios:index'))
        else:
            # Return an 'invalid login' error message.
            return render(request, 'registration/login.html', {
                'error_message': 'Usuario o contraseña incorrectos'
            })


class LogoutView(View):

    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('usuarios:index'))

coordinacion/templates/coordinacion/inicio_coordinadora.html
{% extends 'menu.html' %}
{% block title %}Mis Cursos{% endblock %}


{% block content %}
<h1>Coordinadora</h1>
   Bienvenida Coordinadora
{% endblock %}

cursos/templates/cursos/inicio_curso.html
{% extends 'base.html' %}
{% block title %}Mis Cursos{% endblock %}


{% block content %}
<h1>C++ Básico</h1>
<p><a href="{% url 'usuarios:logout' %}">logout</a></p>
{% endblock %}

cursos/templates/cursos/mis_cursos.html
{% extends 'menu.html' %}
{% block title %}Mis Cursos{% endblock %}


{% block content %}
<h1>Mis cursos</h1>
    <ul>
    {% for curso in cursos %}
        <li>{{ curso.nombre }}</li>
    {% endfor %}
    </ul>
{% endblock %}

cursos/templates/cursos/pagina_error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
</head>
<body>
 {% if error_message %}<small class="red-text"><strong>{{ error_message }}</strong></small>{% endif %}
</body>
</html>

templates/base.html
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
     <title>{% block title %}Niñas Pro Proyecto{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

        {% compress css %}
            <link type="text/x-scss" href="{% static 'scss/style.scss' %}" rel="stylesheet" media="screen">
        {% endcompress %}

    </head>
    <body >
        <main>
            {% block menu %}
            {% endblock %}
            {% block content %}
            {% endblock %}

        </main>
    </body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    {% block scripts %}
    {% endblock %}
</html>

templates/menu.html
{% extends 'base.html' %}
{% load static %}

{% block menu %}
<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Niñas Pro</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>

      <ul id="nav-mobile" class="right hide-on-med-and-down">
          {% for menu_item in user.get_menu_items %}
              <li><a href={{ menu_item.1 }}>{{ menu_item.0 }}</a></li>
          {% endfor %}
        <li><a href="{% url 'usuarios:logout' %}">Salir</a></li>
      </ul>
    </div>
  </nav>

    <ul class="sidenav" id="mobile-demo">
       {% for menu_item in user.get_menu_items %}
              <li><a href={{ menu_item.1 }}>{{ menu_item.0 }}</a></li>
          {% endfor %}
        <li><a href="{% url 'usuarios:logout' %}">Salir</a></li>

    </ul>


{% endblock %}
{% block scripts %}
    <script src={% static 'scripts.js' %}></script>

{% endblock %}